// Auto-generated by pipeline/02_train.py — do not edit manually.
// Re-run 01_filter_extract.py then 02_train.py to regenerate.
#pragma once
#include <stdint.h>

static const int N_FEATURES  = 9;
static const int N_PCA       = 3;
static const int N_CLUSTERS  = 3;
static const int WINDOW_SIZE = 100;   // samples (1 s @ 100 Hz)
static const int HOP_SIZE    = 30;    // on-device inference cadence (independent of training hop in 01_filter_extract.py)
static const int N_SOS       = 2; // biquad sections

// ── StandardScaler ──────────────────────────────────────────────────
// scaled[i] = (raw[i] - SCALER_MEAN[i]) / SCALER_STD[i]
static const float SCALER_MEAN[9] = {0.00199956f, 0.01132181f, 0.04968155f, 0.00000895f, 0.26033083f, 0.02709830f, 0.82044214f, 1.91843641f, 0.00531407f};
static const float SCALER_STD[9] = {0.03529279f, 0.02195207f, 0.07448070f, 0.00059374f, 0.11110795f, 0.01575425f, 0.28064901f, 1.79929984f, 0.00662665f};

// ── PCA projection [N_PCA][N_FEATURES] ─────────────────────────────
// pca[p] = dot(PCA_COMPONENTS[p], scaled_features)
static const float PCA_COMPONENTS[3][9] = {
    {-0.08539191f, 0.40817499f, 0.40253547f, -0.01109324f, -0.39402670f, -0.25052565f, -0.42107865f, 0.50239450f, 0.12734179f},
    {-0.19607405f, 0.37608650f, 0.41466713f, -0.05500407f, 0.26789260f, 0.20046967f, 0.28293875f, -0.28025630f, 0.61203527f},
    {0.60130411f, 0.02314645f, 0.06354271f, 0.71807176f, -0.12774426f, -0.06319598f, -0.08193599f, -0.20762561f, 0.21931410f}
};

// ── K-means centroids [N_CLUSTERS][N_PCA] ──────────────────────────
static const float KMEANS_CENTROIDS[3][3] = {
    {-1.01361549f, 0.08705522f, -0.05858788f},
    {3.91936255f, -0.74788111f, 0.90600348f},
    {9.45049191f, 1.50903594f, -3.28785062f}
};

// ── Biquad IIR filter [N_SOS][5]: {b0, b1, b2, a1, a2} ─────────────
// Direct Form II:  w = x - a1*w1 - a2*w2;  y = b0*w + b1*w1 + b2*w2
// (a0 = 1 is normalised out by scipy)
static const float BIQUAD_SOS[2][5] = {
    {0.16717927f, 0.33435854f, 0.16717927f, 0.32897568f, 0.06458765f},
    {1.00000000f, 2.00000000f, 1.00000000f, 0.45311952f, 0.46632558f}
};

// ── Servo calibration [5]: {PC1, PC2, PC3, spike_count, hjorth_complexity}
// Joint order: S0=spike_count, S1=PC3, S2=PC1, S3=PC2, S4=hjorth_complexity
static const float SERVO_LO[5] = {0.01000000f, -0.41929880f, -1.78275943f, -1.81475365f, 1.27656186f};
static const float SERVO_HI[5] = {0.04000000f, 1.51277649f, 5.63133860f, 2.53421068f, 1.47516859f};

// ── Per-feature PCA weights [N_FEATURES] ───────────────────────────────
// Applied AFTER StandardScaler, BEFORE PCA dot-product.
// weighted[i] = scaled[i] * FEATURE_WEIGHTS[i]
static const float FEATURE_WEIGHTS[9] = {1.00000000f, 1.20000005f, 1.20000005f, 1.00000000f, 1.20000005f, 1.00000000f, 1.20000005f, 1.50000000f, 1.00000000f};
