/**
 * plant_inference.ino  —  PlantCasso ESP32-S3
 * ============================================
 * Real-time plant bioelectric signal → K-means cluster → 5-DOF servo arm.
 *
 * Workflow (triggered every HOP_SIZE=50 new samples = every 500 ms at 100 Hz):
 *
 *   ADC (12-bit, 3.3 V)
 *     → Biquad IIR lowpass  (30 Hz, 4th-order Butterworth, 2 × Direct-Form-II)
 *     → Circular window buffer (WINDOW_SIZE = 100 samples)
 *     → 9 FFT-free features    (matches pipeline/01_filter_extract.py exactly)
 *     → StandardScaler         (subtract SCALER_MEAN, divide by SCALER_STD)
 *     → PCA projection         (9D → 3D via PCA_COMPONENTS dot product)
 *     → K-means nearest centroid
 *     → Servo angle mapping + exponential smoothing
 *
 * Servo mapping:
 *   Joint 0 (shoulder)    ← PC1   (slow, smooth — overall state)
 *   Joint 1 (elbow)       ← PC2
 *   Joint 2 (wrist tilt)  ← PC3
 *   Joint 3 (wrist rotate)← spike_count        (snappy — transient spikes)
 *   Joint 4 (gripper)     ← hjorth_complexity  (chaos / waveform irregularity)
 *
 * Prerequisites:
 *   • model_params.h in the same directory (generated by pipeline/02_train.py)
 *   • Arduino-ESP32 core ≥ 2.0
 *   • ESP32Servo library (install via Arduino Library Manager) — or replace
 *     the servo stub section with your own driver (PCA9685, serial, etc.)
 *
 * Adjust PIN_PLANT and SERVO_PINS to match your wiring.
 */

#include <Arduino.h>
#include <array>
#include <cmath>
#include "model_params.h"

// ─────────────────────────────────────────────────────────────────────────────
// Pin configuration — edit to match your board wiring
// ─────────────────────────────────────────────────────────────────────────────
static constexpr int PIN_PLANT = 11;

// GPIO pins for 5 servo PWM signals (shoulder, elbow, wrist_tilt, wrist_rot, gripper)
// Uncomment and fill in once you attach physical servos:
// #include <ESP32Servo.h>
// static constexpr std::array<int, 5> SERVO_PINS = {1, 2, 3, 4, 5};
// static Servo servo[5];

// ─────────────────────────────────────────────────────────────────────────────
// Sampling timing — 100 Hz
// ─────────────────────────────────────────────────────────────────────────────
static constexpr uint32_t SAMPLE_US = 10'000UL;

// ─────────────────────────────────────────────────────────────────────────────
// Biquad IIR lowpass — Direct Form II (causal, 1 sample latency per section)
// BIQUAD_SOS rows from model_params.h: {b0, b1, b2, a1, a2}   (a0 = 1)
//
//   w[n] = x[n] - a1*w[n-1] - a2*w[n-2]
//   y[n] = b0*w[n] + b1*w[n-1] + b2*w[n-2]
// ─────────────────────────────────────────────────────────────────────────────
struct BiquadState { float w1{0.0f}, w2{0.0f}; };
static std::array<BiquadState, N_SOS> s_bq{};

static float biquad_process(float x) noexcept {
    for (int s = 0; s < N_SOS; ++s) {
        const float *c = BIQUAD_SOS[s];               // {b0, b1, b2, a1, a2}
        float w = x - c[3] * s_bq[s].w1 - c[4] * s_bq[s].w2;
        float y = c[0] * w + c[1] * s_bq[s].w1 + c[2] * s_bq[s].w2;
        s_bq[s].w2 = s_bq[s].w1;
        s_bq[s].w1 = w;
        x = y;
    }
    return x;
}

// ─────────────────────────────────────────────────────────────────────────────
// Circular window buffer — holds the last WINDOW_SIZE filtered samples.
// write_pos always points to where the NEXT sample will be written.
// After the buffer is full, oldest sample is at index write_pos.
// ─────────────────────────────────────────────────────────────────────────────
static std::array<float, WINDOW_SIZE> s_win_buf{};
static int      s_write_pos = 0;
static uint32_t s_n_written = 0;   // total samples ever written

// Copy circular buffer into dst[0..WINDOW_SIZE-1] in oldest→newest order.
static void linearise_window(float *dst) noexcept {
    for (int i = 0; i < WINDOW_SIZE; ++i)
        dst[i] = s_win_buf[(s_write_pos + i) % WINDOW_SIZE];
}

// ─────────────────────────────────────────────────────────────────────────────
// Feature extraction
// MUST match pipeline/01_filter_extract.py::extract_window() exactly.
//
// Feature indices (same order as SCALER_MEAN, SCALER_STD, etc.):
//   0  mean               DC / baseline voltage
//   1  std                overall amplitude variability
//   2  ptp                peak-to-peak (spike amplitude)
//   3  slope              linear drift within window
//   4  zcr                zero-crossing rate of demeaned signal
//   5  spike_count        local-maxima rate above mean + 2σ
//   6  hjorth_mobility    √(var(Δx) / var(x))
//   7  hjorth_complexity  mobility(Δx) / mobility(x)
//   8  rms_first_diff     √(mean(Δx²))  — high-freq content proxy
// ─────────────────────────────────────────────────────────────────────────────
static std::array<float, N_FEATURES> s_raw_feats{};

static void extract_features(const float * __restrict__ w, int n) noexcept {
    const float fn  = static_cast<float>(n);
    const float fn1 = static_cast<float>(n - 1);
    const float fn2 = static_cast<float>(n - 2);

    // ── mean, min, max ────────────────────────────────────────────────────
    float sum = 0.0f, vmin = w[0], vmax = w[0];
    for (int i = 0; i < n; ++i) {
        sum += w[i];
        if (w[i] < vmin) vmin = w[i];
        if (w[i] > vmax) vmax = w[i];
    }
    const float mean = sum / fn;

    // ── std (population variance, ddof=0) ─────────────────────────────────
    float var_sum = 0.0f;
    for (int i = 0; i < n; ++i) {
        const float d = w[i] - mean;
        var_sum += d * d;
    }
    const float var_x = var_sum / fn + 1e-10f;
    const float std_v = sqrtf(var_x);

    // ── slope — analytical linear regression ──────────────────────────────
    // x̄ = (n−1)/2;  Σ(i − x̄)² = n·(n²−1)/12
    const float x_mean = (fn - 1.0f) * 0.5f;
    float xy = 0.0f;
    for (int i = 0; i < n; ++i)
        xy += (static_cast<float>(i) - x_mean) * (w[i] - mean);
    // Note: Σ(i−x̄)·(y_i−ȳ) = Σ(i−x̄)·y_i  since Σ(i−x̄)=0
    const float x_var2 = fn * (fn * fn - 1.0f) / 12.0f;
    const float slope  = xy / x_var2;

    // ── ptp ───────────────────────────────────────────────────────────────
    const float ptp = vmax - vmin;

    // ── zero-crossing rate on demeaned signal ─────────────────────────────
    int zc        = 0;
    int prev_sign = (w[0] - mean >= 0.0f) ? 1 : -1;
    for (int i = 1; i < n; ++i) {
        const int s = (w[i] - mean >= 0.0f) ? 1 : -1;
        if (s != prev_sign) { ++zc; prev_sign = s; }
    }
    const float zcr = static_cast<float>(zc) / fn;

    // ── spike count — sharpness-gated peaks ──────────────────────────────
    // A candidate peak must satisfy ALL of:
    //   (a) local maximum   (b) above mean + SPIKE_SIGMA * std
    //   (c) drops by >= SPIKE_SHARP * std within SPIKE_HALF_WIDTH samples
    //       on EACH side — this rejects slow fluctuations that happen to
    //       crest above the threshold but never come back down quickly.
    // Tune in 01_filter_extract.py and mirror the values here.
    static constexpr float SPIKE_SIGMA      = 1.5f;   // height threshold (σ)
    static constexpr float SPIKE_SHARP      = 0.5f;   // min drop each side (σ)
    static constexpr int   SPIKE_HALF_WIDTH = 3;      // samples — 30 ms @ 100 Hz

    const float thr = mean + SPIKE_SIGMA * std_v;
    int spikes = 0;
    for (int i = SPIKE_HALF_WIDTH; i < n - SPIKE_HALF_WIDTH; ++i) {
        if (w[i] > w[i-1] && w[i] > w[i+1] && w[i] > thr
                && w[i] - w[i - SPIKE_HALF_WIDTH] > SPIKE_SHARP * std_v
                && w[i] - w[i + SPIKE_HALF_WIDTH] > SPIKE_SHARP * std_v)
            ++spikes;
    }
    const float spike_count = static_cast<float>(spikes) / fn;

    // ── Hjorth parameters — single-pass via E[x²]−E[x]² identity ─────────
    // var(dx)  = mean(dx²)  − mean(dx)²   (population variance, ddof=0)
    // var(d²x) = mean(d²x²) − mean(d²x)²
    float dx_sum  = 0.0f, dx_sq_sum  = 0.0f;
    float d2x_sum = 0.0f, d2x_sq_sum = 0.0f;

    for (int i = 0; i < n - 1; ++i) {
        const float dx = w[i+1] - w[i];
        dx_sum    += dx;
        dx_sq_sum += dx * dx;
        if (i < n - 2) {
            const float d2x = w[i+2] - 2.0f * w[i+1] + w[i];
            d2x_sum    += d2x;
            d2x_sq_sum += d2x * d2x;
        }
    }
    const float dx_mean  = dx_sum  / fn1;
    const float d2x_mean = d2x_sum / fn2;
    const float var_dx   = dx_sq_sum  / fn1 - dx_mean  * dx_mean  + 1e-10f;
    const float var_d2x  = d2x_sq_sum / fn2 - d2x_mean * d2x_mean + 1e-10f;

    const float rms_diff   = sqrtf(dx_sq_sum / fn1);
    const float mobility   = sqrtf(var_dx / var_x);
    const float complexity = sqrtf(var_d2x / var_dx) / mobility;

    // ── Store ─────────────────────────────────────────────────────────────
    s_raw_feats[0] = mean;
    s_raw_feats[1] = std_v;
    s_raw_feats[2] = ptp;
    s_raw_feats[3] = slope;
    s_raw_feats[4] = zcr;
    s_raw_feats[5] = spike_count;
    s_raw_feats[6] = mobility;
    s_raw_feats[7] = complexity;
    s_raw_feats[8] = rms_diff;
}

// ─────────────────────────────────────────────────────────────────────────────
// Rolling-mean baseline — ring buffer of the last N_MEAN_WINDOWS window means.
// Feature 0 (mean) becomes deviation from that local baseline:
//   - captures genuine state shifts  (e.g. plant responding to stimulus)
//   - rejects slow DC drift          (electrode offset changing over hours)
//
// N_MEAN_WINDOWS = 10 → baseline spans the last 10 × HOP_SIZE/FS seconds.
// Increase for slower adaptation (more drift tolerance, less state sensitivity).
// Must match N_MEAN_WINDOWS in pipeline/02_train.py.
// ─────────────────────────────────────────────────────────────────────────────
static constexpr int N_MEAN_WINDOWS = 10;
static float  s_mean_ring[N_MEAN_WINDOWS] = {};
static int    s_mean_ring_pos  = 0;    // next write position
static int    s_mean_ring_fill = 0;    // how many slots are filled
static float  s_mean_ring_sum  = 0.0f; // running sum for O(1) mean

// ─────────────────────────────────────────────────────────────────────────────
// Standardise + PCA project
// ─────────────────────────────────────────────────────────────────────────────
static float                         s_win_mean_v = 0.0f;  // raw window mean (V)
static std::array<float, N_FEATURES> s_scaled{};
static std::array<float, N_PCA>      s_pca{};

static void standardise_and_project() noexcept {
    // ── Rolling-mean baseline (ring buffer) ───────────────────────────────
    // Update ring: subtract oldest entry if full, insert current mean.
    if (s_mean_ring_fill == N_MEAN_WINDOWS)
        s_mean_ring_sum -= s_mean_ring[s_mean_ring_pos];  // evict oldest
    s_mean_ring[s_mean_ring_pos] = s_raw_feats[0];
    s_mean_ring_sum += s_raw_feats[0];
    s_mean_ring_pos = (s_mean_ring_pos + 1) % N_MEAN_WINDOWS;
    if (s_mean_ring_fill < N_MEAN_WINDOWS) ++s_mean_ring_fill;

    const float rolling_mean = s_mean_ring_sum / static_cast<float>(s_mean_ring_fill);
    s_win_mean_v    = s_raw_feats[0];  // save absolute window mean before subtraction
    s_raw_feats[0] -= rolling_mean;   // deviation from local N-window baseline

    for (int i = 0; i < N_FEATURES; ++i)
        s_scaled[i] = (s_raw_feats[i] - SCALER_MEAN[i]) / SCALER_STD[i]
                      * FEATURE_WEIGHTS[i];   // boost complexity (index 7) → 2×

    for (int p = 0; p < N_PCA; ++p) {
        float dot = 0.0f;
        for (int f = 0; f < N_FEATURES; ++f)
            dot += PCA_COMPONENTS[p][f] * s_scaled[f];
        s_pca[p] = dot;
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// K-means — nearest centroid (squared Euclidean, avoids sqrtf)
// ─────────────────────────────────────────────────────────────────────────────
[[nodiscard]] static int find_cluster() noexcept {
    int   best      = 0;
    float best_dist = 1e30f;
    for (int k = 0; k < N_CLUSTERS; ++k) {
        float dist = 0.0f;
        for (int p = 0; p < N_PCA; ++p) {
            const float d = s_pca[p] - KMEANS_CENTROIDS[k][p];
            dist += d * d;
        }
        if (dist < best_dist) { best_dist = dist; best = k; }
    }
    return best;
}

// ─────────────────────────────────────────────────────────────────────────────
// Servo mapping + exponential smoothing
// ─────────────────────────────────────────────────────────────────────────────
static constexpr float SERVO_MIN_DEG = 10.0f;
static constexpr float SERVO_MAX_DEG = 170.0f;

// Exponential smoothing per joint.  Lower α = smoother / slower.
// Joints 0-2 follow PCA (slow posture), joints 3-4 follow raw features (fast).
static constexpr std::array<float, 5> SERVO_ALPHA = {0.08f, 0.08f, 0.08f, 0.55f, 0.55f};

static std::array<float, 5> s_servo_pos = {90.0f, 90.0f, 90.0f, 90.0f, 90.0f};

// Map value v from [lo, hi] to [SERVO_MIN_DEG, SERVO_MAX_DEG], clamped.
static float map_servo(float v, float lo, float hi) noexcept {
    if (hi - lo < 1e-6f) return 90.0f;
    float t = (v - lo) / (hi - lo);
    t = (t < 0.0f) ? 0.0f : (t > 1.0f ? 1.0f : t);
    return SERVO_MIN_DEG + t * (SERVO_MAX_DEG - SERVO_MIN_DEG);
}

static void update_servos(int cluster) noexcept {
    // Driving signal for each joint (order matches SERVO_LO / SERVO_HI in header):
    //   0 → PC1   (shoulder)
    //   1 → PC2   (elbow)
    //   2 → PC3   (wrist tilt)
    //   3 → spike_count        (wrist rotate — jumps on spikes)
    //   4 → hjorth_complexity  (gripper — opens during chaotic bursts)
    const float driving[5] = {
        s_pca[0], s_pca[1], s_pca[2],
        s_raw_feats[5],   // spike_count
        s_raw_feats[7],   // hjorth_complexity
    };

    for (int j = 0; j < 5; ++j) {
        float target  = map_servo(driving[j], SERVO_LO[j], SERVO_HI[j]);
        s_servo_pos[j] += SERVO_ALPHA[j] * (target - s_servo_pos[j]);
    }

    // ── Hardware output ───────────────────────────────────────────────────
    // Replace the serial print block below with your servo driver.
    // Example using ESP32Servo (one-liner per joint after setup):
    //     servo[j].write(static_cast<int>(s_servo_pos[j]));
    // ─────────────────────────────────────────────────────────────────────

    Serial.print("C:"); Serial.print(cluster);
    for (int j = 0; j < 5; ++j) {
        Serial.print("  S"); Serial.print(j);
        Serial.print(":"); Serial.print(static_cast<int>(s_servo_pos[j]));
    }
    Serial.print("    mean:");   Serial.print(s_raw_feats[0], 3);
    Serial.print("  spk:");     Serial.print(s_raw_feats[5], 4);
    Serial.print("  chaos:");   Serial.println(s_raw_feats[7], 3);

    Serial.printf("{0:%.4f; 1:%.4f; 2:%.4f; 3:%.4f; 4:%d}\n",
                  s_win_mean_v, s_raw_feats[1], s_raw_feats[5], s_raw_feats[7], cluster);
}

// ─────────────────────────────────────────────────────────────────────────────
// Arduino entry points
// ─────────────────────────────────────────────────────────────────────────────
void setup() {
    Serial.begin(115200);
    uint32_t now = millis();
    uint32_t ref_t = millis();
    while (!Serial) {
        if(ref_t - now > 500) break;
        ref_t = millis();
    }

    analogReadResolution(12);         // 0 – 4095
    analogSetAttenuation(ADC_11db);   // 0 – 3.3 V range

    // Uncomment once servos are wired:
    // for (int j = 0; j < 5; ++j) {
    //     servo[j].attach(SERVO_PINS[j]);
    //     servo[j].write(90);
    // }

    Serial.println("PlantCasso inference ready.");
    Serial.print("k="); Serial.print(N_CLUSTERS);
    Serial.print("  window="); Serial.print(WINDOW_SIZE);
    Serial.print("  hop="); Serial.println(HOP_SIZE);
    Serial.println("C:cluster  S0-S4:servo_deg  mean  spk  chaos");
}

void loop() {
    // ── 100 Hz tick ───────────────────────────────────────────────────────
    static uint32_t last_us = 0;
    const  uint32_t now     = micros();
    if (now - last_us < SAMPLE_US) return;
    last_us = now;

    // ── Sample & filter ───────────────────────────────────────────────────
    const int   raw_adc = analogRead(PIN_PLANT);
    const float volts   = raw_adc * (3.3f / 4095.0f);
    const float filt_v  = biquad_process(volts);

    // ── Write to circular buffer ──────────────────────────────────────────
    s_win_buf[s_write_pos] = filt_v;
    s_write_pos = (s_write_pos + 1) % WINDOW_SIZE;
    ++s_n_written;

    // ── Process window every HOP_SIZE samples once the buffer is full ─────
    if (s_n_written < static_cast<uint32_t>(WINDOW_SIZE)) return;
    if ((s_n_written - static_cast<uint32_t>(WINDOW_SIZE))
            % static_cast<uint32_t>(HOP_SIZE) != 0) return;

    // Place on stack — 100 × 4 bytes = 400 B, well within ESP32-S3 task stack.
    float temp_win[WINDOW_SIZE];
    linearise_window(temp_win);

    extract_features(temp_win, WINDOW_SIZE);
    standardise_and_project();
    const int cluster = find_cluster();
    update_servos(cluster);
}
